using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QtDataTrace.Interfaces
{
    [Serializable]
    public class PLTCM_CoilInfo
    {
        public string OUT_MAT_NO { get; set; }
        public string CUST_OUT_MAT_NO { get; set; }
        public string FINAL_COIL_FLAG { get; set; }
        public string PRODUCT_FLAG { get; set; }
        public string REPAIR_FLAG { get; set; }
        public string REPAIR_COUNT { get; set; }
        public string PLAN_NO { get; set; }
        public string PLAN_TYPE { get; set; }
        public int WHOLE_BACKLOG_SEQ { get; set; }
        public string WHOLE_BACKLOG_CODE { get; set; }
        public int NEXT_WHOLE_BACKLOG_SEQ { get; set; }
        public string NEXT_WHOLE_BACKLOG_CODE { get; set; }
        public string ORDER_NO { get; set; }
        public string ALTER_SPECS_FLAG { get; set; }
        public double OUT_MAT_TARG_LEN { get; set; }
        public double OUT_MAT_TARG_WIDTH { get; set; }
        public double OUT_MAT_TARG_THICK { get; set; }
        public double OUT_MAT_LEN { get; set; }
        public double OUT_MAT_MAX_LEN { get; set; }
        public double OUT_MAT_MIN_LEN { get; set; }
        public double OUT_MAT_WIDTH { get; set; }
        public double OUT_MAT_MAX_WIDTH { get; set; }
        public double OUT_MAT_MIN_WIDTH { get; set; }
        public double OUT_MAT_THICK { get; set; }
        public double OUT_MAT_MAX_THICK { get; set; }
        public double OUT_MAT_MIN_THICK { get; set; }
        public double OUT_MAT_INNER_DIA { get; set; }
        public double OUT_MAT_OUTER_DIA { get; set; }
        public double OUT_MAT_THEORY_WT { get; set; }
        public double OUT_MAT_ACT_WT { get; set; }
        public string WT_MODE { get; set; }
        public string OUT_MAT_USE_SLEEVE_FLAG { get; set; }
        public string SLEEVE_NO { get; set; }
        public string IN_MAT_NO_1 { get; set; }
        public string CUST_IN_MAT_NO_1 { get; set; }
        public double IN_MAT_1_LEN { get; set; }
        public double IN_MAT_1_WIDTH { get; set; }
        public double IN_MAT_1_THICK { get; set; }
        public double IN_MAT_1_USE_WT { get; set; }
        public string IN_MAT_NO_2 { get; set; }
        public string CUST_IN_MAT_NO_2 { get; set; }
        public double IN_MAT_2_LEN { get; set; }
        public double IN_MAT_2_WIDTH { get; set; }
        public double IN_MAT_2_THICK { get; set; }
        public double IN_MAT_2_USE_WT { get; set; }
        public DateTime START_TIME { get; set; }
        public DateTime STOP_TIME { get; set; }
        public string PERSIST_PROD_TIME { get; set; }
        public string PROD_SHIFT_NO { get; set; }
        public string PROD_SHIFT_GROUP { get; set; }
        public string HOLD_FLAG { get; set; }
        public string HOLD_CAUSE_CODE { get; set; }
        public string HOLD_MAKER { get; set; }
        public int SCRAP_LEN_HEAD { get; set; }
        public int SCRAP_WT_HEAD { get; set; }
        public int SCRAP_LEN_TAIL { get; set; }
        public int SCRAP_WT_TAIL { get; set; }
        public string TRIM_FLAG { get; set; }
        public double ACT_TRIM_WIDTH { get; set; }
        public string WELD_POSITION_1 { get; set; }
        public string WELD_POSITION_2 { get; set; }
        public string WELD_POSITION_3 { get; set; }
        public string REC_ERASE_TIME { get; set; }
        public double OUT_MAT_GROSS_WT { get; set; }
        public double OUT_MAT_CAL_GROSS_WT { get; set; }
        public string PO_NO { get; set; }
        public string ST_NO { get; set; }
        public string SG_SIGN { get; set; }
        public string SURFACE_DECIDE_MAKER { get; set; }
        public string SURFACE_DECIDE_CODE { get; set; }
        public string BETTER_SURF_WARD_CODE { get; set; }
        public string SURF_PROTECT_CODE { get; set; }
        public string SURFACE_ACCU_CODE { get; set; }
        public string SCRAP_CODE_HEAD { get; set; }
        public string SCRAP_CODE_TAIL { get; set; }
        public int PROD_STOP_TIME { get; set; }
        public int PROD_STOP_NUM { get; set; }
        public string MAT_UNION_FLAG { get; set; }
        public string HOT_FLAG { get; set; }
        public string TENSION_FLAG { get; set; }
        public int TENSION_ELONG_AVG { get; set; }
        public int TENSION_ELONG_MAX { get; set; }
        public int TENSION_ELONG_MIN { get; set; }
        public string TPM_MODE { get; set; }
        public double TPM_RATE_AVG { get; set; }
        public double TPM_RATE_MAX { get; set; }
        public double TPM_RATE_MIN { get; set; }
        public string OIL_KIND_CODE { get; set; }
        public string OIL_QTY_CODE { get; set; }
        public int MILL_SPEED_AVG { get; set; }
        public int MILL_SPEED_MAX { get; set; }
        public int MILL_SPEED_MIN { get; set; }
        public int TEMP_PICKLING_1 { get; set; }
        public int TEMP_PICKLING_2 { get; set; }
        public int TEMP_PICKLING_3 { get; set; }
        public int TEMP_RINSE_TANK_4 { get; set; }
        public int ACID_CONCE_1 { get; set; }
        public int ACID_CONCE_2 { get; set; }
        public int ACID_CONCE_3 { get; set; }
        public int ACID_CONCE_4 { get; set; }
        public int FE_CONCENTATION_1 { get; set; }
        public int FE_CONCENTATION_2 { get; set; }
        public int FE_CONCENTATION_3 { get; set; }
        public int FE_CONCENTATION_4 { get; set; }
        public int HOT_WATER_PRES { get; set; }
        public int TEMP_RINSE_TANK { get; set; }
        public int RINSE_TANK { get; set; }
        public int RINSE_TANK_PH { get; set; }
        public double HEAD_OFF_GAUGE_LEN { get; set; }
        public double MID_OFF_GAUGE_LEN { get; set; }
        public double TAIL_OFF_GAUGE_LEN { get; set; }
        public double HEAD_OFF_GAUGE_LEN_01 { get; set; }
        public double MID_OFF_GAUGE_LEN_01 { get; set; }
        public double TAIL_OFF_GAUGE_LEN_01 { get; set; }
        public double HEAD_OFF_GAUGE_LEN_02 { get; set; }
        public double MID_OFF_GAUGE_LEN_02 { get; set; }
        public double TAIL_OFF_GAUGE_LEN_02 { get; set; }
        public int ENTRY_TENSION_S1 { get; set; }
        public int TENSION_S1_S2 { get; set; }
        public int TENSION_S2_S3 { get; set; }
        public int TENSION_S3_S4 { get; set; }
        public int TENSION_S4_S5 { get; set; }
        public int OUT_TENSION_S5 { get; set; }
        public int TOP_ROLL_ROUGH_S5 { get; set; }
        public int BOT_ROLL_ROUGH_S5 { get; set; }
        public double LG_DEPRQUO_S1 { get; set; }
        public double LG_DEPRQUO_S2 { get; set; }
        public double LG_DEPRQUO_S3 { get; set; }
        public double LG_DEPRQUO_S4 { get; set; }
        public double LG_DEPRQUO_S5 { get; set; }
        public double LG_DEPRQUO_PLTCM { get; set; }
        public int HEAD_SCAPE_LEN_1 { get; set; }
        public int HEAD_SCAPE_WT_1 { get; set; }
        public int BOT_SCAPE_LEN_1 { get; set; }
        public int BOT_SCAPE_WT_1 { get; set; }
        public int HEAD_SCAPE_LEN_2 { get; set; }
        public int HEAD_SCAPE_WT_2 { get; set; }
        public int BOT_SCAPE_LEN_2 { get; set; }
        public int BOT_SCAPE_WT_2 { get; set; }
        public string ORDER_NO_ITEM { get; set; }
        public double IN_MAT_1_WT { get; set; }
        public double IN_MAT_2_WT { get; set; }
        public double IN_MAT_WT { get; set; }
        public double PO_THICK { get; set; }
        public double EXIT_THICK_AVG { get; set; }
        public double EXIT_WIDTH_AVG { get; set; }
        public double PO_WIDTH { get; set; }
        public string SY_FLAG { get; set; }

    }
}
